name: Update Py File Count

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script to count .py files and update README
        run: bash update_py_file_count.sh

      - name: Set up Git
        run: |
          git config user.email "viviserrao03@gmail.com"
          git config user.name "ViniciusGurgel"
      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update .py file count [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
